import {openStore,allRecords,saveRecord,seed} from './storage.js';
import {recognize,plain,dateValue} from './recognition.js';
import {demoData} from './demo-data.js';
import {icon} from './icons.js';
const $=s=>document.querySelector(s), main=$('#main');
for(const [nav,name] of Object.entries({today:'home',new:'plus',records:'records',ideas:'bulb'}))document.querySelector(`nav [data-nav="${nav}"] .nav-symbol`).innerHTML=icon(name);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=[],page='today',statusFilter='Otvorené',typeFilter='Všetky typy',priorityFilter='Všetky priority',categoryFilter='Všetky kategórie',query='',expanded=false,advancedFilters=false,draft=null,urls=[],voice=null,photoBusy=false,selected=new Set(),pendingImport=[];
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function url(blob){const u=URL.createObjectURL(blob);urls.push(u);return u;}
function cleanup(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];}
function dueLabel(r){if(!r.due)return 'Bez termínu';const today=dateValue(new Date());const d=new Date(`${r.due}T12:00:00`);return `${r.due===today?'Dnes':d.toLocaleDateString('sk-SK')}${r.time?' · '+r.time:''}${r.due<today?' · po termíne':''}`;}
function priorityClass(r){return r.done?'done':r.type==='Nápad'?'idea':r.priority==='Vysoká'?'high':r.priority==='Nízka'?'low':'';}
function badge(r){return `<span class="badge ${priorityClass(r)}">${r.done?'Hotové':r.type==='Nápad'?'Nápad':r.priority}</span>`;}
function card(r,shareable=false){
  const selectedControl=shareable?`<label class="record-select"><input type="checkbox" data-select="${esc(r.id)}" ${selected.has(r.id)?'checked':''} aria-label="Vybrať záznam: ${esc(r.text)}"></label>`:'';
  const photoControl=r.photo?`<button data-photo="${esc(r.id)}" aria-label="Otvoriť fotografiu" class="card-photo"><img class="thumb" alt="Fotografia záznamu" src="${url(r.photo)}"></button>`:'';
  const calendarControl=shareable&&!r.done&&r.type!=='Nápad'&&r.due&&r.due>=dateValue(new Date())?`<button class="calendar-button" data-calendar="${esc(r.id)}">▣ Kalendár</button>`:'';
  const controls=`<div class="card-actions">${photoControl}${calendarControl}${shareable?`<button class="share-button" data-share="${esc(r.id)}">↗ Zdieľať</button>`:''}${!r.done?`<button class="done-button" data-done="${esc(r.id)}">✓ Hotovo</button>`:''}</div>`;
  const mark=r.done?'✓':r.type==='Nápad'?'♧':r.priority==='Vysoká'?'!':r.priority==='Nízka'?'↓':r.type==='Nákup'?'▣':r.type==='Poznámka'?'✎':'▤';
  return `<article class="card ${r.done?'completed':''} ${shareable?'selectable':''} ${selected.has(r.id)?'selected':''}">${selectedControl}<span class="card-icon ${priorityClass(r)}" aria-hidden="true">${mark}</span><button class="card-main" data-detail="${esc(r.id)}" aria-label="Otvoriť: ${esc(r.text)}"><span class="card-title">${esc(r.place||r.type)}</span><span class="card-text">${esc(r.text.length>105?r.text.slice(0,102)+'…':r.text)}</span><span class="card-meta">${badge(r)}<span>${esc(r.type==='Nápad'||r.type==='Poznámka'&&!r.due?new Date(r.createdAt).toLocaleDateString('sk-SK'):dueLabel(r))}</span></span></button>${controls}</article>`;
}
function list(items,shareable=false){return items.length?items.map(r=>card(r,shareable)).join(''):'<div class="empty">Žiadne záznamy. Máte tu voľné miesto na ďalší postreh.</div>';}
function actions(){return `<div class="actions"><button class="action" data-mode="voice"><span class="symbol">${icon('mic')}</span>Povedať</button><button class="action photo" data-mode="photo"><span class="symbol">${icon('camera')}</span>Odfotiť + povedať</button><button class="action write" data-mode="write"><span class="symbol">${icon('pen')}</span>Napísať</button></div>`;}
function priorityRank(priority){return priority==='Vysoká'?0:priority==='Nízka'?2:1;}
function todayRecords(){const today=dateValue(new Date());return records.filter(r=>{if(r.done||r.type==='Nápad'||r.type==='Poznámka')return false;if(r.priority==='Vysoká')return true;if(r.priority==='Nízka')return !!r.due&&r.due<=today;return !r.due||r.due<=today;}).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||(a.due||'9999').localeCompare(b.due||'9999')||(a.time||'99').localeCompare(b.time||'99'));}
function filterButton(value){return `<button class="filter ${statusFilter===value?'active':''}" aria-pressed="${statusFilter===value}" data-status-filter="${value}">${value}</button>`;}
function filterSelect(id,label,current,values){return `<div><label for="${id}">${label}</label><select id="${id}">${values.map(value=>`<option ${current===value?'selected':''}>${value}</option>`).join('')}</select></div>`;}
function render(){cleanup();document.querySelectorAll('[data-nav]').forEach(b=>{b.classList.toggle('active',b.dataset.nav===page);b.setAttribute('aria-current',b.dataset.nav===page?'page':'false');});
  if(page==='today'){const items=todayRecords(),high=items.filter(r=>r.priority==='Vysoká').length,ideas=records.filter(r=>r.type==='Nápad'&&!r.done).length;main.innerHTML=`<p class="eyebrow">DOBRÉ RÁNO, ČO DNES VYBAVÍME?</p><h1>Dnešný prehľad</h1><p class="subtitle">${new Date().toLocaleDateString('sk-SK',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><div class="page-grid"><section><div class="summary"><h2>Dnes treba vybaviť ${items.length} ${items.length===1?'vec':'vecí'}</h2><div class="stats"><div><strong class="red">${high}</strong><span>vysoká priorita</span></div><div><strong>${items.length-high}</strong><span>ostatné dnes</span></div><div><strong class="green">${ideas}</strong><span>nápady bokom</span></div></div></div>${actions()}<p class="hint">Zapíšte si myšlienku, kým ju máte v hlave.<br>Stačí jedna veta, ostatné navrhneme.</p></section><section><h2>Najdôležitejšie dnes</h2><div class="cards">${list(expanded?items:items.slice(0,3))}</div>${items.length>3?`<button class="more" id="more">${expanded?'Zobraziť menej':`Zobraziť ďalšie ${items.length-3} ↓`}</button>`:''}<p class="hint">Otvorené úlohy a nákupy po termíne, na dnes a bez termínu. Vysoká priorita sa zobrazí aj s neskorším termínom; nízka bez termínu zostáva vo Všetkých záznamoch.</p></section></div>`;}
  if(page==='records'){main.innerHTML=`<h1>Všetky záznamy</h1><p class="subtitle">Úlohy, poznámky a nákupy na jednom mieste.</p><input class="search" id="search" type="search" aria-label="Hľadať záznam" placeholder="Hľadať text, kategóriu alebo miesto…" value="${esc(query)}"><div class="filters simple-filters">${['Otvorené','Po termíne','Hotové'].map(filterButton).join('')}<button class="secondary more-filters" id="toggle-filters" aria-expanded="${advancedFilters}">⚙ Ďalšie filtre</button></div><div class="advanced-filters" id="advanced-filters" ${advancedFilters?'':'hidden'}><div class="filter-grid">${filterSelect('type-filter','Typ',typeFilter,['Všetky typy','Úloha','Poznámka','Nákup','Nápad'])}${filterSelect('priority-filter','Priorita',priorityFilter,['Všetky priority','Vysoká','Normálna','Nízka'])}${filterSelect('category-filter','Kategória',categoryFilter,['Všetky kategórie','Osobné','Rodina','Domácnosť','Práca','Nákupy','Zdravie','Financie','Cestovanie'])}</div><button class="secondary" id="clear-filters">Vyčistiť ďalšie filtre</button></div><div class="share-toolbar"><button class="secondary" id="import-record">⇩ Importovať záznam</button><button class="secondary" id="select-all">☐ Vybrať všetky</button><button class="share-selected" id="share-selected" disabled>↗ Zdieľať vybrané</button></div><p class="hint" id="result-count"></p><div class="cards" id="results"></div>`;renderResults();}
  if(page==='ideas'){const items=records.filter(r=>r.type==='Nápad'&&!r.done).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));main.innerHTML=`<h1>Nápady a zlepšenia</h1><p class="subtitle">Dobré myšlienky si zaslúžia vlastné miesto.</p><div class="summary idea-banner"><h2>♧ ${items.length} ${items.length===1?'nápad':'nápadov'} na neskôr</h2><p>Veci, ktoré netreba riešiť hneď.</p></div><button id="add-idea" class="primary full">＋ Pridať nápad</button><h2>Posledné nápady</h2><div class="cards">${list(items)}</div>`;}
  if(page==='new')renderForm();
}
function visibleRecords(){const today=dateValue(new Date());return records.filter(r=>{const match=plain(`${r.text} ${r.place} ${r.category} ${r.type}`).includes(plain(query));const statusMatch=statusFilter==='Hotové'?r.done:statusFilter==='Po termíne'?!r.done&&!!r.due&&r.due<today:!r.done;const typeMatch=typeFilter==='Všetky typy'||r.type===typeFilter;const priorityMatch=priorityFilter==='Všetky priority'||r.priority===priorityFilter;const categoryMatch=categoryFilter==='Všetky kategórie'||r.category===categoryFilter;return match&&statusMatch&&typeMatch&&priorityMatch&&categoryMatch;}).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||(a.due||'9999').localeCompare(b.due||'9999')||b.createdAt.localeCompare(a.createdAt));}
function renderResults(){const items=visibleRecords(),visibleIds=new Set(items.map(r=>r.id));selected=new Set([...selected].filter(id=>visibleIds.has(id)));$('#results').innerHTML=list(items,true);$('#result-count').textContent=`Počet nájdených záznamov: ${items.length}`;updateShareToolbar();}
function updateShareToolbar(){if(page!=='records'||!$('#share-selected'))return;const items=visibleRecords(),all=items.length>0&&items.every(r=>selected.has(r.id));$('#select-all').disabled=!items.length;$('#select-all').textContent=all?'☑ Zrušiť výber':'☐ Vybrať všetky';$('#share-selected').disabled=!selected.size;$('#share-selected').textContent=`↗ Zdieľať vybrané${selected.size?` (${selected.size})`:''}`;document.querySelectorAll('[data-select]').forEach(input=>input.closest('.card').classList.toggle('selected',input.checked));}
function sharedText(items){return `Môj zápisník\n\n${items.map((r,i)=>`${i+1}. ${r.priority==='Vysoká'?'[VYSOKÁ PRIORITA] ':r.priority==='Nízka'?'[NÍZKA PRIORITA] ':''}${r.text}\nTyp: ${r.type} | Kategória: ${r.category} | Miesto: ${r.place||'neuvedené'} | Termín: ${dueLabel(r)} | Stav: ${r.done?'Hotovo':'Otvorené'}`).join('\n\n')}`;}
function showShareFallback(text){$('#share-text').value=text;$('#share-dialog').showModal();$('#share-text').select();}
const SHARE_APP='moj-zapisnik',SHARE_FORMAT='zapisnik-share';
function exportedRecord(r,photo=null){return {sourceId:r.id,text:r.text,type:r.type,category:r.category,priority:r.priority,place:r.place||'',due:r.due||'',time:r.time||'',done:!!r.done,photo};}
function encodePayload(value){const bytes=new TextEncoder().encode(JSON.stringify(value));let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');}
function decodePayload(value){const base=value.replaceAll('-','+').replaceAll('_','/').padEnd(Math.ceil(value.length/4)*4,'=');const binary=atob(base);return JSON.parse(new TextDecoder().decode(Uint8Array.from(binary,char=>char.charCodeAt(0))));}
function shareEnvelope(items){return {format:SHARE_FORMAT,version:1,app:SHARE_APP,records:items};}
function shareLink(record){return `${location.href.split('#')[0]}#import=${encodePayload(shareEnvelope([exportedRecord(record)]))}`;}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}
async function createShareFile(items){const exported=[];for(const record of items)exported.push(exportedRecord(record,record.photo?await blobToDataUrl(record.photo):null));const stamp=new Date().toISOString().slice(0,10);return new File([JSON.stringify(shareEnvelope(exported))],`moj-zapisnik-${stamp}.json`,{type:'application/json'});}
function downloadBlob(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
async function shareRecords(items){
  if(!items.length){toast('Najskôr vyberte aspoň jeden záznam.');return;}
  const text=sharedText(items),needsFile=items.length>1||items.some(r=>r.photo),data={title:items.length===1?'Záznam z môjho zápisníka':`Môj zápisník – ${items.length} záznamy`,text};
  let file=null;if(needsFile){file=await createShareFile(items);if(navigator.canShare?.({files:[file]}))data.files=[file];}else data.url=shareLink(items[0]);
  if(navigator.share&&(!needsFile||data.files)){try{await navigator.share(data);toast(needsFile?'Zdieľací súbor bol odoslaný.':'Zdieľací odkaz bol odoslaný.');return;}catch(e){if(e.name==='AbortError')return;}}
  if(file){downloadBlob(file,file.name);toast('Zdieľací súbor je stiahnutý. Pošlite ho cez e-mail alebo chat.');return;}
  const copy=`${text}\n\nPridať do aplikácie: ${data.url}`;try{await navigator.clipboard.writeText(copy);toast('Zdieľací odkaz je skopírovaný. Vložte ho do e-mailu alebo chatu.');}catch{showShareFallback(copy);}
}
function validDate(value){if(value==='')return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const [y,m,d]=value.split('-').map(Number),date=new Date(y,m-1,d);return date.getFullYear()===y&&date.getMonth()===m-1&&date.getDate()===d;}
function dataUrlToBlob(value){if(!value)return null;const match=/^data:(image\/[a-z0-9.+-]+);base64,([a-z0-9+/=]+)$/i.exec(value);if(!match||value.length>22*1024*1024)throw new Error('Fotografia v súbore nie je platná alebo je príliš veľká.');const binary=atob(match[2]),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return new Blob([bytes],{type:match[1]});}
function readImportEnvelope(value){
  if(value?.format!==SHARE_FORMAT||value.version!==1||value.app!==SHARE_APP||!Array.isArray(value.records)||!value.records.length||value.records.length>100)throw new Error('Tento súbor nepatrí do Môjho zápisníka.');
  const types=['Úloha','Poznámka','Nákup','Nápad'],categories=['Osobné','Rodina','Domácnosť','Práca','Nákupy','Zdravie','Financie','Cestovanie'],priorities=['Vysoká','Normálna','Nízka'];
  return value.records.map(raw=>{if(typeof raw.text!=='string'||!raw.text.trim()||raw.text.length>3000||!types.includes(raw.type)||!categories.includes(raw.category)||!priorities.includes(raw.priority)||typeof raw.place!=='string'||raw.place.length>120||typeof raw.due!=='string'||!validDate(raw.due)||typeof raw.time!=='string'||!/^$|^(?:[01]\d|2[0-3]):[0-5]\d$/.test(raw.time))throw new Error('Zdieľaný záznam má neplatné údaje.');return {sourceId:String(raw.sourceId||''),text:raw.text.trim(),type:raw.type,category:raw.category,priority:raw.priority,place:raw.place,due:raw.due,time:raw.time,done:!!raw.done,photo:dataUrlToBlob(raw.photo)};});
}
function showImport(items){pendingImport=items;const preview=items.slice(0,3).map(item=>`<div><strong>${esc(item.text)}</strong><span>${esc(item.type)} • ${esc(item.priority)} • ${esc(item.due?dueLabel(item):'Bez termínu')}${item.photo?' • s fotografiou':''}</span></div>`).join('');$('#import-summary').innerHTML=preview+(items.length>3?`<p>…a ďalšie ${items.length-3}</p>`:'');$('#import-dialog').showModal();}
async function importPending(){let added=0,skipped=0;for(const item of pendingImport){const source=`${SHARE_APP}:${item.sourceId}`;if(item.sourceId&&records.some(r=>r.id===item.sourceId||r.importSource===source)){skipped++;continue;}const {sourceId,...data}=item;await saveRecord({...data,id:crypto.randomUUID(),importSource:sourceId?source:'',createdAt:new Date().toISOString()});added++;}pendingImport=[];$('#import-dialog').close();records=await allRecords();page='records';statusFilter='Otvorené';render();toast(added?`Pridané záznamy: ${added}.${skipped?` Preskočené duplikáty: ${skipped}.`:''}`:'Tento záznam už v aplikácii máte.');}
function importFromHash(){if(!location.hash.startsWith('#import='))return;const encoded=location.hash.slice(8);history.replaceState(null,'',location.href.split('#')[0]);try{showImport(readImportEnvelope(decodePayload(encoded)));}catch(error){toast(error.message||'Zdieľací odkaz sa nepodarilo otvoriť.');}}
function icsEscape(value){return String(value??'').replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;');}
function foldIcsLine(line){const chars=Array.from(line),parts=[];while(chars.length)parts.push(chars.splice(0,50).join(''));return parts.join('\r\n ');}
function localIcsDate(date){return `${date.getFullYear()}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}${String(date.getMinutes()).padStart(2,'0')}00`;}
function addToCalendar(record){const start=new Date(`${record.due}T${record.time||'08:00'}:00`),end=new Date(start.getTime()+60*60*1000),stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Moj zapisnik//SK','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${icsEscape(record.id)}@moj-zapisnik.local`,`DTSTAMP:${stamp}`,`DTSTART:${localIcsDate(start)}`,`DTEND:${localIcsDate(end)}`,`SUMMARY:${icsEscape(record.text.slice(0,120))}`,`DESCRIPTION:${icsEscape(`${record.text}\nKategória: ${record.category}\nMiesto: ${record.place||'neuvedené'}`)}`,'BEGIN:VALARM','ACTION:DISPLAY','TRIGGER:-P3D',`DESCRIPTION:${icsEscape(`O 3 dni: ${record.text.slice(0,100)}`)}`,'END:VALARM','BEGIN:VALARM','ACTION:DISPLAY','TRIGGER:PT0M',`DESCRIPTION:${icsEscape(record.text.slice(0,100))}`,'END:VALARM','END:VEVENT','END:VCALENDAR',''];const file=new Blob([lines.map(foldIcsLine).join('\r\n')],{type:'text/calendar;charset=utf-8'});downloadBlob(file,`termin-${record.due}.ics`);toast('Kalendár je pripravený. Otvorte stiahnutý súbor a potvrďte Uložiť.');}
function newDraft(type){return {text:'',...recognize(''),...(type?{type}:{}),photo:null,manual:!!type};}
function renderForm(){if(!draft)draft=newDraft();main.innerHTML=`<h1>${draft.id?'Upraviť záznam':'Nový záznam'}</h1><p class="subtitle">Stačí si rýchlo zachytiť, čo nechcete zabudnúť.</p>${actions()}<div id="voice-note" role="status"></div><form id="record-form"><div class="form-card"><label for="text">Čo si chcete zapísať?</label><textarea id="text" required maxlength="3000" placeholder="Napríklad: Zajtra ráno zavolať zubárovi.">${esc(draft.text)}</textarea><p class="hint">V testovacej verzii používajte vymyslené údaje a necitlivé fotografie.</p><input type="file" id="photo-input" accept="image/*" capture="environment" hidden><div class="record-tools"><button type="button" class="secondary" id="add-photo">▣ ${draft.photo?'Zmeniť fotografiu':'Pridať fotografiu'}</button><button type="button" class="secondary" id="edit-fields" aria-controls="fields" aria-expanded="false">Upraviť údaje</button><button type="button" id="recognize-again" class="secondary">Znovu rozpoznať z textu</button></div><div id="photo-preview"></div></div><div class="form-card"><span class="recognition-title">✦ Návrh zaradenia</span><p class="recognition-summary" id="recognized"></p><div id="fields" hidden><p class="hint">Ručné úpravy sa už neprepíšu rozpoznávaním. „Znovu rozpoznať“ obnoví návrh z textu. Ráno znamená 08:00 a večer 18:00.</p><div class="field-grid">${selectField('type','Typ',['Úloha','Poznámka','Nákup','Nápad'])}${selectField('category','Kategória',['Osobné','Rodina','Domácnosť','Práca','Nákupy','Zdravie','Financie','Cestovanie'])}${selectField('priority','Priorita',['Vysoká','Normálna','Nízka'])}<div><label for="place">Miesto / oblasť</label><input id="place" maxlength="120" value="${esc(draft.place)}"></div><div><label for="due">Termín</label><input id="due" type="date" value="${esc(draft.due)}"></div><div><label for="time">Čas</label><input id="time" type="time" value="${esc(draft.time)}"></div></div></div></div><div id="form-error" role="alert"></div><div class="form-footer"><button class="primary" type="submit" id="save">Uložiť záznam</button><button type="button" class="secondary" id="cancel">Zrušiť</button></div></form>`;updateSummary();photoPreview();}
function showFields(open){$('#fields').hidden=!open;$('#edit-fields').setAttribute('aria-expanded',String(open));if(open){$('#fields').scrollIntoView({block:'nearest'});$('#type').focus({preventScroll:true});}}
function selectField(id,label,options){return `<div><label for="${id}">${label}</label><select id="${id}">${options.map(v=>`<option ${draft[id]===v?'selected':''}>${v}</option>`).join('')}</select></div>`;}
function updateSummary(){if(!$('#recognized'))return;$('#recognized').textContent=[draft.type,draft.category,draft.priority+' priorita',draft.place||'Miesto neuvedené',dueLabel(draft)].join(' • ');}
function syncFields(){for(const key of ['type','category','priority','place','due','time'])$('#'+key).value=draft[key];updateSummary();}
function autoRecognize(){if(!draft.manual){Object.assign(draft,recognize(draft.text));syncFields();}}
function photoPreview(){const target=$('#photo-preview');if(!target)return;target.innerHTML=draft.photo?`<div class="photo-preview"><button type="button" id="preview-draft" aria-label="Zväčšiť fotografiu"><img alt="Pridaná fotografia" src="${url(draft.photo)}"></button><span class="hint">1 fotografia pridaná</span><button type="button" id="remove-photo">Odobrať</button></div>`:'';}
function showPhoto(blob){$('#large-photo').src=url(blob);$('#photo-dialog').showModal();}
function detail(id){const r=records.find(r=>r.id===id);if(!r)return;cleanup();page='detail';const calendar=!r.done&&r.type!=='Nápad'&&r.due&&r.due>=dateValue(new Date())?`<button class="calendar-button" data-calendar="${esc(r.id)}">▣ Pridať do kalendára</button>`:'';main.innerHTML=`<button class="secondary back" data-nav="records">← Všetky záznamy</button><h1>${esc(r.place||r.type)}</h1><p class="subtitle">${esc(r.type)} · ${esc(r.category)}</p><div class="form-card">${badge(r)}<p class="detail-text">${esc(r.text)}</p><p class="hint">Termín: ${esc(dueLabel(r))}<br>Vytvorené: ${new Date(r.createdAt).toLocaleString('sk-SK')}</p>${r.photo?`<button class="detail-photo" data-photo="${esc(r.id)}" aria-label="Zväčšiť fotografiu"><img src="${url(r.photo)}" alt="Fotografia tohto záznamu"></button><p class="hint">Kliknutím fotografiu zväčšíte.</p>`:''}${calendar?'<p class="hint">Kalendár pripomenie termín tri dni vopred a v deň termínu.</p>':''}</div><div class="detail-actions"><button class="primary" data-done="${esc(r.id)}">${r.done?'Znovu otvoriť':'✓ Hotovo'}</button><button class="secondary" data-edit="${esc(r.id)}">Upraviť záznam</button>${calendar}<button class="share-button" data-share="${esc(r.id)}">↗ Zdieľať</button></div>`;}
function navigate(target){if(page==='new'&&draft&&(draft.text.trim()||draft.photo)&&!confirm('Opustiť neuložený záznam?'))return;voice?.abort();voice=null;draft=null;if(target!=='records')selected.clear();page=target;render();window.scrollTo(0,0);}
async function startVoice(){const note=$('#voice-note');const tell=t=>{if(note?.isConnected){note.className='voice-note';note.textContent=t;}};if(voice){voice.stop();return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
  if(!SR||!('processLocally' in SR.prototype)||!SR.available){tell('Hlas priamo v tomto zariadení nie je dostupný. Poznámku napíšte do poľa nižšie. Zvuk neodosielame externej službe.');$('#text').focus();return;}
  try{const status=await SR.available({langs:['sk-SK'],processLocally:true});if(!note.isConnected)return;if(status!=='available'){tell('Slovenčina pre miestne rozpoznávanie nie je dostupná. Použite písanie; žiadnu službu nepripájame ani nič nesťahujeme.');$('#text').focus();return;}voice=new SR();voice.lang='sk-SK';voice.processLocally=true;voice.interimResults=false;const current=draft;voice.onresult=e=>{if(draft!==current)return;draft.text=(draft.text+' '+e.results[0][0].transcript).trim().slice(0,3000);$('#text').value=draft.text;autoRecognize();tell('Text je pripravený. Skontrolujte ho a uložte.');};voice.onerror=()=>tell('Hlas sa nepodarilo zachytiť. Skontrolujte povolenie mikrofónu alebo poznámku napíšte.');voice.onend=()=>{voice=null;if(note.textContent.startsWith('Počúvam'))tell('Počúvanie sa skončilo. Skontrolujte text alebo ho dopíšte.');};voice.start();tell('Počúvam… Opätovným stlačením Povedať ukončíte počúvanie.');}catch{voice=null;tell('Hlas nie je k dispozícii. Poznámku môžete napísať.');}}
async function addPhoto(file){if(!file)return;const current=draft;photoBusy=true;$('#save').disabled=true;try{if(!file.type.startsWith('image/'))throw new Error('Vyberte obrázok JPG, PNG alebo iný podporovaný obrázok.');if(file.size>20*1024*1024)throw new Error('Fotografia je príliš veľká. Vyberte obrázok do 20 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob)throw new Error('Obrázok sa nepodarilo spracovať.');if(draft!==current)return;draft.photo=blob;photoPreview();toast('Fotografia pridaná. Doplňte postreh a uložte.');}catch(e){toast(e.message||'Fotografiu sa nepodarilo načítať. Skúste JPG alebo PNG.');}finally{photoBusy=false;if($('#save'))$('#save').disabled=false;}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
  if(b.dataset.nav){navigate(b.dataset.nav);return;}
  if(b.dataset.mode){if(page!=='new'){draft=newDraft();page='new';render();}if(b.dataset.mode==='photo')$('#photo-input').click();else if(b.dataset.mode==='voice')await startVoice();else $('#text').focus();return;}
  if(b.dataset.detail){detail(b.dataset.detail);return;}
  if(b.dataset.photo){showPhoto(records.find(r=>r.id===b.dataset.photo).photo);return;}
  if(b.dataset.share){await shareRecords([records.find(r=>r.id===b.dataset.share)]);return;}
  if(b.dataset.calendar){addToCalendar(records.find(r=>r.id===b.dataset.calendar));return;}
  if(b.dataset.done){const r=records.find(r=>r.id===b.dataset.done);const updated={...r,done:!r.done};await saveRecord(updated);records=await allRecords();if(page==='detail')detail(r.id);else render();toast(updated.done?'Označené ako hotovo.':'Záznam je znovu otvorený.');return;}
  if(b.dataset.edit){draft={...records.find(r=>r.id===b.dataset.edit),manual:true};page='new';render();return;}
  if(b.dataset.statusFilter){statusFilter=b.dataset.statusFilter;selected.clear();render();return;}
  if(b.id==='toggle-filters'){advancedFilters=!advancedFilters;render();return;}
  if(b.id==='clear-filters'){typeFilter='Všetky typy';priorityFilter='Všetky priority';categoryFilter='Všetky kategórie';selected.clear();render();return;}
  if(b.id==='import-record'){$('#import-input').click();return;}
  if(b.id==='select-all'){const items=visibleRecords(),all=items.length&&items.every(r=>selected.has(r.id));items.forEach(r=>all?selected.delete(r.id):selected.add(r.id));renderResults();return;}
  if(b.id==='share-selected'){await shareRecords(visibleRecords().filter(r=>selected.has(r.id)));return;}
  if(b.id==='more'){expanded=!expanded;render();}
  if(b.id==='add-idea'){draft=newDraft('Nápad');page='new';render();$('#text').focus();}
  if(b.id==='add-photo')$('#photo-input').click();
  if(b.id==='edit-fields')showFields($('#fields').hidden);
  if(b.id==='remove-photo'){draft.photo=null;photoPreview();}
  if(b.id==='preview-draft')showPhoto(draft.photo);
  if(b.id==='close-photo')$('#photo-dialog').close();
  if(b.id==='close-share')$('#share-dialog').close();
  if(b.id==='select-share-text'){$('#share-text').select();toast('Text je označený. Použite Kopírovať.');}
  if(b.id==='confirm-import'){await importPending();return;}
  if(b.id==='cancel-import'){pendingImport=[];$('#import-dialog').close();return;}
  if(b.id==='cancel')navigate('today');
  if(b.id==='recognize-again'){draft.manual=false;autoRecognize();toast('Návrh zaradenia bol obnovený z textu.');}
}catch(e){toast('Operácia sa nepodarila. '+e.message);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;selected.clear();renderResults();}if(e.target.id==='text'){draft.text=e.target.value;autoRecognize();}if(['type','category','priority','place','due','time'].includes(e.target.id)){draft[e.target.id]=e.target.value;draft.manual=true;updateSummary();}});
document.addEventListener('change',async e=>{
  if(e.target.id==='photo-input')addPhoto(e.target.files[0]);
  if(e.target.id==='type-filter'){typeFilter=e.target.value;selected.clear();renderResults();}
  if(e.target.id==='priority-filter'){priorityFilter=e.target.value;selected.clear();renderResults();}
  if(e.target.id==='category-filter'){categoryFilter=e.target.value;selected.clear();renderResults();}
  if(e.target.id==='import-input'){const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>25*1024*1024)throw new Error('Zdieľací súbor je príliš veľký.');showImport(readImportEnvelope(JSON.parse(await file.text())));}catch(error){toast(error.message||'Zdieľací súbor sa nepodarilo otvoriť.');}}
  if(e.target.matches('[data-select]')){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);updateShareToolbar();}
});
document.addEventListener('submit',async e=>{if(e.target.id!=='record-form')return;e.preventDefault();if(photoBusy)return;if(!draft.text.trim()){$('#text').focus();toast('Doplňte krátky text k záznamu.');return;}if(draft.time&&!draft.due){showFields(true);$('#due').focus();toast('K času doplňte dátum alebo čas vymažte.');return;}const button=$('#save');button.disabled=true;try{voice?.abort();const {manual,...data}=draft;await saveRecord({...data,text:data.text.trim(),id:data.id||crypto.randomUUID(),createdAt:data.createdAt||new Date().toISOString(),done:data.done||false});records=await allRecords();const savedType=draft.type;draft=null;page=savedType==='Nápad'?'ideas':'records';statusFilter='Otvorené';typeFilter='Všetky typy';priorityFilter='Všetky priority';categoryFilter='Všetky kategórie';query='';render();window.scrollTo(0,0);toast('Záznam je uložený.');}catch{$('#form-error').innerHTML='<p class="error">Uloženie sa nepodarilo. Text zostal vo formulári. Skontrolujte voľné miesto a povolenie ukladania v prehliadači.</p>';button.disabled=false;}});
window.addEventListener('beforeunload',e=>{if(page==='new'&&draft&&(draft.text.trim()||draft.photo)){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',importFromHash);
try{await openStore();await seed(demoData());records=await allRecords();render();importFromHash();}catch(e){main.innerHTML=`<h1>Úložisko nie je dostupné</h1><p class="error">${esc(e.message)} Otvorte aplikáciu v bežnom okne prehliadača a povoľte ukladanie údajov.</p>`;}
